parser: "babel-eslint"
extends: "airbnb"
env:
  browser: true
  node: true
  mocha: true

globals:
  gilt: false
  requireSpecs: false
  getJSONString: false
  describe: false
  xdescribe: false
  it: false
  xit: false
  expect: false
  jasmine: false
  spyOn: false
  afterEach: false
  beforeEach: false
  waits: false
  waitsFor: false
  runs: false
  sinon: false

rules:
  # Overriding AirBnb style guide (some of their rules are a bit too strict)
  react/prefer-es6-class: 1
  react/no-unused-prop-types: [2, { skipShapeProps: true }]
  comma-dangle: 0
  func-names: 0
  no-param-reassign: 0
  global-require: 0
  jsx-quotes: [2, "prefer-single"]
  space-before-function-paren: 0
  no-bitwise: 0
  no-plusplus: 0
  strict: 0
  default-case: 1
  no-void: 1

  # Rules commented out because are currently switched of below
  # (Avoiding duplicate entry warning)
  # prefer-arrow-callback: 1
  # quote-props: [1, "as-needed", {
  #   keywords: false
  #   unnecessary: true
  #   numbers: false
  # }]
  # prefer-template: 1
  # no-unused-vars: 1
  # one-var: [1, "always"]
  # no-var: 1
  # object-shorthand: [1, "always", { avoidQuotes: true }]


  # These two rules slow down the linting process considerably.
  # Switching them off to have a better coding experience (at least on Atom)
  import/no-named-as-default: "off"
  import/no-named-as-default-member: "off"
